a = imread('1.jpg'); 
A = rgb2gray(a); 
B = imnoise(A, 'salt & pepper'); 
C = imnoise(A,'gaussian'); 
f1 = 1/9 * ones(3, 3); 
f2 = 1/25 * ones(5, 5); 
f3 = 1/49 * ones(7, 7); 
B1 = imfilter(B, f1, 'same'); 
B2 = imfilter(B, f2, 'same'); 
B3 = imfilter(B, f3, 'same'); 
C1 = imfilter(B1, f1, 'same'); 
C2 = imfilter(B2, f2, 'same'); 
C3 = imfilter(B3, f3, 'same'); 
D1 = imfilter(C1, f1, 'same'); 
D2 = imfilter(C2, f2, 'same'); 
D3 = imfilter(C3, f3, 'same'); 
subplot(2, 3, 1), imshow(a), title('original image'); 
subplot(2, 3, 2), imshow(B), title('salt and pepper'); 
subplot(2, 3, 3), imshow(B), title('Gaussian'); 
subplot(2, 3, 4), imshow(uint8(B1)), title('After applying 3*3'); 
subplot(2, 3, 5), imshow(uint8(B2)), title('After applying 5*5'); 
subplot(2, 3, 6), imshow(uint8(B3)), title('After applying 7*7');